---
title: "Experience"
toc: false
page-layout: full
---

### Professional Summary

-   10+ years of experience in experiment design and assay development
-   Experience antibody and soluble protein developability, production, purification & QC
-   Experience in CRISPR-based gene editing in mammalian cell lines (KO and KI)
-   Development and selection of stable clonal cell lines using PiggyBac system
-   Experience in hybridoma, yeast display screen, and 8-color flow cytometry
-   AKTA based purification and optimization of proteins using affinity columns
-   Experience with antibody target validation and affinity maturation
-   Characterize protein interaction and kinetics using ELISA, SPR, and BLI
-   Proficient in data analysis, statistical tests, visualization, and presentation in R/ Python
-   Establishing new and reviewing SOPs and laboratory protocols
-   Effective communication, organizational skills, record keeping
-   Ability to learn quickly, work independently, and train colleagues

### Senior Research Scientist, MassBiologics

##### 2020 - Present

-   Project manager and lead in developing novel antibodies and proteins for non-human primate (NHP) preclinical studies
-   Optimization of bispecific, multispecific, and alternative antibody formats
-   Multicolor flow cytometry and panel generation for primate blood
-   Generation of high producing stable clonal cell lines for antibodies and protein production
-   Improve antibody yield and function by gene editing
-   Characterizing protein-protein interaction using ELISA and kinetics using SPR and BLI
-   Establishing new and reviewing SOPs and laboratory protocols
-   Training colleagues & research associates

### Scientist II, Totient Inc.

##### 2018 - 2020

-   Served as cell and molecular biology lead for oncology drug discovery programs
-   Developed strategies to simultaneously knockout two genes using CRISPR-Cas9
-   Experience with preparation of high-quality whole genome lentiviral sgRNA particles
-   Identification of targets using CRISPR mediated whole genome knockout screen on multiple cell lines
-   Identification of targets for recombinant antibodies using Protein arrays, ELISA and immunofluorescence
-   Worked with CROs with for special assays including 3D cell culture and SPR (Biacore)
-   Managed one direct report

### Postdoctoral Associate, University of Massachusetts Medical School

##### 2018

-   Developing a CRISPR screen to identify novel epigenetic regulators in Ewing’s Sarcoma
-   Executing genome wide shRNA/ RNAi and proteomic screens to identify regulators in X-chromosome inactivation pathway
-   Genome editing by CRISPR/Cas9 for specific projects in the lab
-   Managed one intern and two junior graduate students
